version: '3'
services:
  php:
          image: php:7-fpm
          network_mode: "host"
          ports:
            - 9000:9000
          volumes:
            - ./code:/code 
  nginx:
          image: nginx:latest
          network_mode: "host"
          ports:
            - 443:443
            - 8080:8080
          volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt
            - ./nginx/nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key
            - ./code:/code
  varnish:
          image: varnish:latest
          network_mode: "host"
          volumes:
            - ./varnish/varnish.vcl:/etc/varnish/conf.d/default.vcl